name: build-test
on: pull_request
jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: install dependencies
        run: bun install
        working-directory: ./app
      - name: run tests
        run: bun test
        working-directory: ./app
      - name: run build
        run: bun run build
        working-directory: ./app
